$axure.loadCurrentPage({
  "url":"设置页面.html",
  "generationDate":new Date(1464254034830.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4727481d60524a5481eba2b57e6e7883",
    "type":"Axure:Page",
    "name":"设置页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aeabc0e963084bc68c2015c4be6f6ec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":3},
            "size":{
              "width":185,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd13a5d52664e92a96072ab1262304a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":3},
                "size":{
                  "width":185,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fa0d84fefc64b2e82a3408712ce6b67",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":120},
            "size":{
              "width":118,
              "height":190}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 setttings",
                      "objectsToFades":[{
                          "objectPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 setttings to 视频设置",
                      "panelsToStates":[{
                          "panelPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"25e24981bd2148dc802e943fd5d95fc3",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7ef91a18679440e3bda83f26f2ece9be",
                  "label":"",
                  "parentDynamicPanel":"5fa0d84fefc64b2e82a3408712ce6b67",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":160},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8dcd3f98195c44febfb8b60491d6d446",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa0d84fefc64b2e82a3408712ce6b67",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":160},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c4b5614cf61e4ccb84bee36a0a5cfc67",
                  "label":"",
                  "parentDynamicPanel":"5fa0d84fefc64b2e82a3408712ce6b67",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"474d3c2bc5af436bb0577b2dd5d83e00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa0d84fefc64b2e82a3408712ce6b67",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":0},
                        "size":{
                          "width":110,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9bf63096f9b945d8ab74702fbc30b294",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":120},
            "size":{
              "width":114,
              "height":190}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 setttings to 音频设置",
                      "panelsToStates":[{
                          "panelPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 setttings",
                      "objectsToFades":[{
                          "objectPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5bff95dd7939483ea65d3044c7faa229",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4cfaedcd570f443889a68d0ae96dd927",
                  "label":"",
                  "parentDynamicPanel":"9bf63096f9b945d8ab74702fbc30b294",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":160},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"104eb88507b94caaba39950bf48b51b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9bf63096f9b945d8ab74702fbc30b294",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":160},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"25668926263a4f33aa6a66e8a6febf20",
                  "label":"",
                  "parentDynamicPanel":"9bf63096f9b945d8ab74702fbc30b294",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11664a7e645249fdbec101b3ad2ad53e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9bf63096f9b945d8ab74702fbc30b294",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":0},
                        "size":{
                          "width":110,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"001e80f09fb64086a5a6b2a9997fbebd",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":120},
            "size":{
              "width":114,
              "height":190}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 setttings",
                      "objectsToFades":[{
                          "objectPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 setttings to 网络设置",
                      "panelsToStates":[{
                          "panelPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":4,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f6bb8cb674764a1e9a8cc4ad5a59c11b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b9336adb62754d2dbf5fb96025d90bf8",
                  "label":"",
                  "parentDynamicPanel":"001e80f09fb64086a5a6b2a9997fbebd",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":160},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"582bca12636c493ca770e5005f9d55bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"001e80f09fb64086a5a6b2a9997fbebd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":160},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4e56c4ee3be348b8b4cae1d3b4ff43d6",
                  "label":"",
                  "parentDynamicPanel":"001e80f09fb64086a5a6b2a9997fbebd",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"922b18c4784243d08c9d5368fd9c99f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"001e80f09fb64086a5a6b2a9997fbebd",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":0},
                        "size":{
                          "width":110,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"bab87f16b19e4b43a5b1010a75891c59",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":117,
              "height":190}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 setttings",
                      "objectsToFades":[{
                          "objectPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 setttings to 基本参数",
                      "panelsToStates":[{
                          "panelPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fdc241c2e6d547fa84b0ea39928f9523",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"19d6e2eafa0340b7a931f2a6252c7364",
                  "label":"",
                  "parentDynamicPanel":"bab87f16b19e4b43a5b1010a75891c59",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"796d5d92a1db4e0a80f983b9c7ccdfe9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bab87f16b19e4b43a5b1010a75891c59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":0},
                        "size":{
                          "width":110,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u5.png"}},
{
                  "id":"467c3b47be114f67a01f8b381c9e6be6",
                  "label":"",
                  "parentDynamicPanel":"bab87f16b19e4b43a5b1010a75891c59",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":34,
                      "y":160},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6a39a00d6844268ba838088b7fd7920",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bab87f16b19e4b43a5b1010a75891c59",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":34,
                          "y":160},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"b64ff7446157463d937da5386ec1135b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":10},
            "size":{
              "width":40,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b97bf4e6fee4c429c6db40532e25e08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":10},
                "size":{
                  "width":40,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 欢迎页面",
                      "target":{
                        "targetType":"page",
                        "url":"欢迎页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置页面/u22.png"}},
{
          "id":"26b0014ae3db45eb88aadb6e39a289d1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":546,
              "y":120},
            "size":{
              "width":114,
              "height":190}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 setttings",
                      "objectsToFades":[{
                          "objectPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 setttings to 直播设置",
                      "panelsToStates":[{
                          "panelPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":5,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9e28ac4638f74b5d9a75408842b82e8b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"18ab9aab3eb943a59db637cacb0789dc",
                  "label":"",
                  "parentDynamicPanel":"26b0014ae3db45eb88aadb6e39a289d1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"400",
                    "location":{
                      "x":22,
                      "y":160},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba8a2b050e704d4b8c642f1f3757c14f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"26b0014ae3db45eb88aadb6e39a289d1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontWeight":"400",
                        "location":{
                          "x":22,
                          "y":160},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"56c345fe220f4427bbee8c75e5a49fad",
                  "label":"",
                  "parentDynamicPanel":"26b0014ae3db45eb88aadb6e39a289d1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f7152d5328e4b81b33b8b806f93617c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"26b0014ae3db45eb88aadb6e39a289d1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":0},
                        "size":{
                          "width":110,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"eeb1e4b14971435f87e8cd800e1fc219",
          "label":"setttings",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":23.5,
              "y":75},
            "size":{
              "width":653,
              "height":280},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 setttings",
                      "objectsToFades":[{
                          "objectPath":["eeb1e4b14971435f87e8cd800e1fc219"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a29a2fce831e43aca204a47a60cbda4b",
              "label":"基本参数",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ba9d01ebf034a7aaf148a9a3bbc0330",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":510,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"003a4a2f87de44608db879e3f6b5a9ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":510,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u30.png"}},
{
                  "id":"865191dfc01e4fc4a21735f5491a4846",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":23},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"021a9cd4d4724908b5986bbd0695368c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":23},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3698d2d10f4243d5bc2c8b0d08508d3d",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":140,
                      "y":20},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"6bc99ad127024a9caae0c93e4a9a9770",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":73},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c241908a4e0c4ba793057cef0ff563f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":73},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"155b598e63dd46548ae1bdf12a3e73c5",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":140,
                      "y":70},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"9de4eab1c154442d848c63ce5ee28189",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":128},
                    "size":{
                      "width":180,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e73ba286893c407b835cea4eb98062ec",
              "label":"视频设置",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"249955853d7f4f89ac48be5941da939e",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":510,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1fe6b48836fe48a289fce58e550b907c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":510,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u30.png"}},
{
                  "id":"87402f936e23425a8b0c013089edac6e",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":23},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"909fd5b017f940ee8bb8ad4d38082504",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":23},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"87feae7b8a5e4be486b7a18ea4e4f698",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":66},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b71d2422f6f47a997db9ccf5e11d4fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":66},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a4a0b602db6e47d485c228e5ec6c2b07",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":113},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"068d72529f834cb78ed5478dae6e66d6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":113},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"adab20bdc94d42b5acac7e33b2e87bc3",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":110},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"d7b8ea187b934b9daa3d8546bfcc260b",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":163},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"802d850ec0f044608fbf8cbde7e27daf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":163},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1c939040471c4da28c700225f8f5d954",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":140,
                      "y":160},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"79c88dedeb874ad4ac3a6b95d5c4c2b6",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":140,
                      "y":22},
                    "size":{
                      "width":330,
                      "height":32}},
                  "adaptiveStyles":{
}},
{
                  "id":"8b580e05d16c4a4e88e5ff5b24d5cae1",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":140,
                      "y":64},
                    "size":{
                      "width":330,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e3f607b741d74bb5bef63244257c91f4",
              "label":"音频设置",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4f53599fb65f430a95f579116f5cb52b",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":510,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"129773d1a929496486fb43c588c4f3d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":510,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u30.png"}},
{
                  "id":"76e4be78084040cc98623d8a50b8e4bc",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":64},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33334e06dd7c4e97b436f4c4119e9496",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":64},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"277005619c024ece8d07302c77861f37",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":107},
                    "size":{
                      "width":61,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fca71edadea74053ac885e9d7753ec9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":107},
                        "size":{
                          "width":61,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"53d3c344ccaa48e6810bc4b372e4b9c6",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":154},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28a688ddfe074f8ca0eb4d7020be5221",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":154},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ef74aaee18e4497ca36e0e8a475db7ab",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":151},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"dcf190a139b649309774705c0a26a6f7",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":204},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d067241f845a42d3bfa38ade4cc49650",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":204},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a2bbf590c93a4bfabb0da9350419ceb3",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":140,
                      "y":62},
                    "size":{
                      "width":330,
                      "height":32}},
                  "adaptiveStyles":{
}},
{
                  "id":"deca1380396644a3a57cfe8799340b4b",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":140,
                      "y":104},
                    "size":{
                      "width":330,
                      "height":32}},
                  "adaptiveStyles":{
}},
{
                  "id":"0a71a0bd3666420ab5fc003041bbee1a",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":140,
                      "y":201},
                    "size":{
                      "width":330,
                      "height":32}},
                  "adaptiveStyles":{
}},
{
                  "id":"cd021ec12dbf4f18b0af576d9053717b",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":29,
                      "y":22},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85a9be9c369d437282c704d8fbb26798",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":29,
                          "y":22},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ee01056143cc4ee1916ac82b7e6c7636",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":140,
                      "y":20},
                    "size":{
                      "width":330,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"81306166841d44e092b7322bc0d0fb35",
              "label":"网络设置",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5026c5bbf8d743ca810a391e4917e9f3",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":510,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29d9d274be01452d84f9da9881fac8cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":510,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u30.png"}},
{
                  "id":"4d174deb31a64205ad4bf2cfee898cac",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":141,
                      "y":56},
                    "size":{
                      "width":130,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5fccbd427754473b4bdef3a5ee79aef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":141,
                          "y":56},
                        "size":{
                          "width":130,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"d586abc6882a45338951acedfee66951",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":311,
                      "y":53},
                    "size":{
                      "width":130,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12ed9974c63e4d6fa095bd2ccc3d04cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":311,
                          "y":53},
                        "size":{
                          "width":130,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"19a117ae963849fab26870f2d15c0a2e",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":40,
                      "y":83},
                    "size":{
                      "width":41,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"610090fbc37040cdb5d69097e2323e62",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":40,
                          "y":83},
                        "size":{
                          "width":41,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e137cdfebead47b28f6fc0aa2440cdb3",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":80},
                    "size":{
                      "width":340,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"9a20360bbe8c4f6abafd7f4620f41b76",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":40,
                      "y":123},
                    "size":{
                      "width":41,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db3c9efefd4445de92d5c1f154d8f8aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":40,
                          "y":123},
                        "size":{
                          "width":41,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1ffaae447b8c41b59f540c08dda3a139",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":120},
                    "size":{
                      "width":340,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"300198e0baf84ca48187e1d829b6a813",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":40,
                      "y":166},
                    "size":{
                      "width":41,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9cbb475a281a422eaa4d5ef26b917681",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":40,
                          "y":166},
                        "size":{
                          "width":41,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b92c722e91314be7a077c50942a93c7c",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":163},
                    "size":{
                      "width":340,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"5aab03ba3ca94d17ae26a36923c3dfe7",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":40,
                      "y":206},
                    "size":{
                      "width":41,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ccdf68fc602b4bd4b5fd25be20425ae1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":40,
                          "y":206},
                        "size":{
                          "width":41,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"42bd0af310154a248b918c6b47056980",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":203},
                    "size":{
                      "width":340,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"09bbce9ef40749faaf785619dea3c6a2",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":43,
                      "y":26},
                    "size":{
                      "width":41,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c7df723e2364f1cb1aba47b7f3f9096",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":43,
                          "y":26},
                        "size":{
                          "width":41,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0aa294df1a194dc49879a6b93cd9767e",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":19},
                    "size":{
                      "width":340,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"f2167cacb1e3472db2e9dfae5aef70d1",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"400",
                    "fontStyle":"normal",
                    "location":{
                      "x":141,
                      "y":19},
                    "size":{
                      "width":340,
                      "height":32}},
                  "adaptiveStyles":{
}},
{
                  "id":"adec89d51e5541b89204ff17a75746bc",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":43,
                      "y":53},
                    "size":{
                      "width":100,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b83e1e897ac340cda4c260d7c4773778",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":43,
                          "y":53},
                        "size":{
                          "width":100,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ae6bd3625c8447e0aec2846e018f059a",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":370,
                      "y":240},
                    "size":{
                      "width":111,
                      "height":32}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"9147f14a583d4a11bbe484f67787fe42",
              "label":"直播设置",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f7e8e7afdb284921bf1787ccf6bec04f",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":510,
                      "height":280}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9f520e36e3c4509bcebf1657b3f7270",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":510,
                          "height":280}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/设置页面/u30.png"}},
{
                  "id":"1bcf1fd9ec1247f5ae8cef5a1a140cd5",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "location":{
                      "x":30,
                      "y":53},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10c6202d4acb40f0ba08b7816b58320e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "location":{
                          "x":30,
                          "y":53},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"baf8a87a95b646d6b6b047f06d95a2ce",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":141,
                      "y":50},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"89b0083b3b6a434693473fedcabed2c7",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "location":{
                      "x":30,
                      "y":103},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8a6e4a285714d3c921430429f138a33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "location":{
                          "x":30,
                          "y":103},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bbe024ce59e64b47a606c206c6ade5b6",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":100},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"f037713ba057432d817ce1e24234fb6e",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":14,
                      "y":14},
                    "size":{
                      "width":61,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1b6974bcb00420da4c65380b49a7bdf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":14,
                          "y":14},
                        "size":{
                          "width":61,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cf1f5a61287f4d4783215a1a1ace897c",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":14,
                      "y":150},
                    "size":{
                      "width":61,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59e88cf3ed744212a8cafecc782f978c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":14,
                          "y":150},
                        "size":{
                          "width":61,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"02f990273f9542859aa35851a2d4b399",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":185},
                    "size":{
                      "width":101,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"527b078f7c9d44ffad608c31e1f5f428",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":185},
                        "size":{
                          "width":101,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7c7594f490dd4761aab5b112b9b972ce",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":182},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}},
{
                  "id":"d22c19b0baff4b74917da5bcc0fa8f61",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":235},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f09907c87da345ee958bab4d7e356b8a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":235},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"64ade33859bb42fba901ddc1425ae1f1",
                  "label":"",
                  "parentDynamicPanel":"eeb1e4b14971435f87e8cd800e1fc219",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":141,
                      "y":232},
                    "size":{
                      "width":330,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "aeabc0e963084bc68c2015c4be6f6ec4":{
      "scriptId":"u0"},
    "cbd13a5d52664e92a96072ab1262304a":{
      "scriptId":"u1"},
    "5fa0d84fefc64b2e82a3408712ce6b67":{
      "scriptId":"u2"},
    "7ef91a18679440e3bda83f26f2ece9be":{
      "scriptId":"u3"},
    "8dcd3f98195c44febfb8b60491d6d446":{
      "scriptId":"u4"},
    "c4b5614cf61e4ccb84bee36a0a5cfc67":{
      "scriptId":"u5"},
    "474d3c2bc5af436bb0577b2dd5d83e00":{
      "scriptId":"u6"},
    "9bf63096f9b945d8ab74702fbc30b294":{
      "scriptId":"u7"},
    "4cfaedcd570f443889a68d0ae96dd927":{
      "scriptId":"u8"},
    "104eb88507b94caaba39950bf48b51b2":{
      "scriptId":"u9"},
    "25668926263a4f33aa6a66e8a6febf20":{
      "scriptId":"u10"},
    "11664a7e645249fdbec101b3ad2ad53e":{
      "scriptId":"u11"},
    "001e80f09fb64086a5a6b2a9997fbebd":{
      "scriptId":"u12"},
    "b9336adb62754d2dbf5fb96025d90bf8":{
      "scriptId":"u13"},
    "582bca12636c493ca770e5005f9d55bc":{
      "scriptId":"u14"},
    "4e56c4ee3be348b8b4cae1d3b4ff43d6":{
      "scriptId":"u15"},
    "922b18c4784243d08c9d5368fd9c99f6":{
      "scriptId":"u16"},
    "bab87f16b19e4b43a5b1010a75891c59":{
      "scriptId":"u17"},
    "19d6e2eafa0340b7a931f2a6252c7364":{
      "scriptId":"u18"},
    "796d5d92a1db4e0a80f983b9c7ccdfe9":{
      "scriptId":"u19"},
    "467c3b47be114f67a01f8b381c9e6be6":{
      "scriptId":"u20"},
    "e6a39a00d6844268ba838088b7fd7920":{
      "scriptId":"u21"},
    "b64ff7446157463d937da5386ec1135b":{
      "scriptId":"u22"},
    "4b97bf4e6fee4c429c6db40532e25e08":{
      "scriptId":"u23"},
    "26b0014ae3db45eb88aadb6e39a289d1":{
      "scriptId":"u24"},
    "18ab9aab3eb943a59db637cacb0789dc":{
      "scriptId":"u25"},
    "ba8a2b050e704d4b8c642f1f3757c14f":{
      "scriptId":"u26"},
    "56c345fe220f4427bbee8c75e5a49fad":{
      "scriptId":"u27"},
    "5f7152d5328e4b81b33b8b806f93617c":{
      "scriptId":"u28"},
    "eeb1e4b14971435f87e8cd800e1fc219":{
      "scriptId":"u29"},
    "0ba9d01ebf034a7aaf148a9a3bbc0330":{
      "scriptId":"u30"},
    "003a4a2f87de44608db879e3f6b5a9ed":{
      "scriptId":"u31"},
    "865191dfc01e4fc4a21735f5491a4846":{
      "scriptId":"u32"},
    "021a9cd4d4724908b5986bbd0695368c":{
      "scriptId":"u33"},
    "3698d2d10f4243d5bc2c8b0d08508d3d":{
      "scriptId":"u34"},
    "6bc99ad127024a9caae0c93e4a9a9770":{
      "scriptId":"u35"},
    "c241908a4e0c4ba793057cef0ff563f7":{
      "scriptId":"u36"},
    "155b598e63dd46548ae1bdf12a3e73c5":{
      "scriptId":"u37"},
    "9de4eab1c154442d848c63ce5ee28189":{
      "scriptId":"u38"},
    "249955853d7f4f89ac48be5941da939e":{
      "scriptId":"u39"},
    "1fe6b48836fe48a289fce58e550b907c":{
      "scriptId":"u40"},
    "87402f936e23425a8b0c013089edac6e":{
      "scriptId":"u41"},
    "909fd5b017f940ee8bb8ad4d38082504":{
      "scriptId":"u42"},
    "87feae7b8a5e4be486b7a18ea4e4f698":{
      "scriptId":"u43"},
    "1b71d2422f6f47a997db9ccf5e11d4fe":{
      "scriptId":"u44"},
    "a4a0b602db6e47d485c228e5ec6c2b07":{
      "scriptId":"u45"},
    "068d72529f834cb78ed5478dae6e66d6":{
      "scriptId":"u46"},
    "adab20bdc94d42b5acac7e33b2e87bc3":{
      "scriptId":"u47"},
    "d7b8ea187b934b9daa3d8546bfcc260b":{
      "scriptId":"u48"},
    "802d850ec0f044608fbf8cbde7e27daf":{
      "scriptId":"u49"},
    "1c939040471c4da28c700225f8f5d954":{
      "scriptId":"u50"},
    "79c88dedeb874ad4ac3a6b95d5c4c2b6":{
      "scriptId":"u51"},
    "8b580e05d16c4a4e88e5ff5b24d5cae1":{
      "scriptId":"u52"},
    "4f53599fb65f430a95f579116f5cb52b":{
      "scriptId":"u53"},
    "129773d1a929496486fb43c588c4f3d0":{
      "scriptId":"u54"},
    "76e4be78084040cc98623d8a50b8e4bc":{
      "scriptId":"u55"},
    "33334e06dd7c4e97b436f4c4119e9496":{
      "scriptId":"u56"},
    "277005619c024ece8d07302c77861f37":{
      "scriptId":"u57"},
    "fca71edadea74053ac885e9d7753ec9a":{
      "scriptId":"u58"},
    "53d3c344ccaa48e6810bc4b372e4b9c6":{
      "scriptId":"u59"},
    "28a688ddfe074f8ca0eb4d7020be5221":{
      "scriptId":"u60"},
    "ef74aaee18e4497ca36e0e8a475db7ab":{
      "scriptId":"u61"},
    "dcf190a139b649309774705c0a26a6f7":{
      "scriptId":"u62"},
    "d067241f845a42d3bfa38ade4cc49650":{
      "scriptId":"u63"},
    "a2bbf590c93a4bfabb0da9350419ceb3":{
      "scriptId":"u64"},
    "deca1380396644a3a57cfe8799340b4b":{
      "scriptId":"u65"},
    "0a71a0bd3666420ab5fc003041bbee1a":{
      "scriptId":"u66"},
    "cd021ec12dbf4f18b0af576d9053717b":{
      "scriptId":"u67"},
    "85a9be9c369d437282c704d8fbb26798":{
      "scriptId":"u68"},
    "ee01056143cc4ee1916ac82b7e6c7636":{
      "scriptId":"u69"},
    "5026c5bbf8d743ca810a391e4917e9f3":{
      "scriptId":"u70"},
    "29d9d274be01452d84f9da9881fac8cf":{
      "scriptId":"u71"},
    "4d174deb31a64205ad4bf2cfee898cac":{
      "scriptId":"u72"},
    "a5fccbd427754473b4bdef3a5ee79aef":{
      "scriptId":"u73"},
    "d586abc6882a45338951acedfee66951":{
      "scriptId":"u74"},
    "12ed9974c63e4d6fa095bd2ccc3d04cf":{
      "scriptId":"u75"},
    "19a117ae963849fab26870f2d15c0a2e":{
      "scriptId":"u76"},
    "610090fbc37040cdb5d69097e2323e62":{
      "scriptId":"u77"},
    "e137cdfebead47b28f6fc0aa2440cdb3":{
      "scriptId":"u78"},
    "9a20360bbe8c4f6abafd7f4620f41b76":{
      "scriptId":"u79"},
    "db3c9efefd4445de92d5c1f154d8f8aa":{
      "scriptId":"u80"},
    "1ffaae447b8c41b59f540c08dda3a139":{
      "scriptId":"u81"},
    "300198e0baf84ca48187e1d829b6a813":{
      "scriptId":"u82"},
    "9cbb475a281a422eaa4d5ef26b917681":{
      "scriptId":"u83"},
    "b92c722e91314be7a077c50942a93c7c":{
      "scriptId":"u84"},
    "5aab03ba3ca94d17ae26a36923c3dfe7":{
      "scriptId":"u85"},
    "ccdf68fc602b4bd4b5fd25be20425ae1":{
      "scriptId":"u86"},
    "42bd0af310154a248b918c6b47056980":{
      "scriptId":"u87"},
    "09bbce9ef40749faaf785619dea3c6a2":{
      "scriptId":"u88"},
    "7c7df723e2364f1cb1aba47b7f3f9096":{
      "scriptId":"u89"},
    "0aa294df1a194dc49879a6b93cd9767e":{
      "scriptId":"u90"},
    "f2167cacb1e3472db2e9dfae5aef70d1":{
      "scriptId":"u91"},
    "adec89d51e5541b89204ff17a75746bc":{
      "scriptId":"u92"},
    "b83e1e897ac340cda4c260d7c4773778":{
      "scriptId":"u93"},
    "ae6bd3625c8447e0aec2846e018f059a":{
      "scriptId":"u94"},
    "f7e8e7afdb284921bf1787ccf6bec04f":{
      "scriptId":"u95"},
    "d9f520e36e3c4509bcebf1657b3f7270":{
      "scriptId":"u96"},
    "1bcf1fd9ec1247f5ae8cef5a1a140cd5":{
      "scriptId":"u97"},
    "10c6202d4acb40f0ba08b7816b58320e":{
      "scriptId":"u98"},
    "baf8a87a95b646d6b6b047f06d95a2ce":{
      "scriptId":"u99"},
    "89b0083b3b6a434693473fedcabed2c7":{
      "scriptId":"u100"},
    "f8a6e4a285714d3c921430429f138a33":{
      "scriptId":"u101"},
    "bbe024ce59e64b47a606c206c6ade5b6":{
      "scriptId":"u102"},
    "f037713ba057432d817ce1e24234fb6e":{
      "scriptId":"u103"},
    "e1b6974bcb00420da4c65380b49a7bdf":{
      "scriptId":"u104"},
    "cf1f5a61287f4d4783215a1a1ace897c":{
      "scriptId":"u105"},
    "59e88cf3ed744212a8cafecc782f978c":{
      "scriptId":"u106"},
    "02f990273f9542859aa35851a2d4b399":{
      "scriptId":"u107"},
    "527b078f7c9d44ffad608c31e1f5f428":{
      "scriptId":"u108"},
    "7c7594f490dd4761aab5b112b9b972ce":{
      "scriptId":"u109"},
    "d22c19b0baff4b74917da5bcc0fa8f61":{
      "scriptId":"u110"},
    "f09907c87da345ee958bab4d7e356b8a":{
      "scriptId":"u111"},
    "64ade33859bb42fba901ddc1425ae1f1":{
      "scriptId":"u112"}}});