$axure.loadCurrentPage({
  "url":"查看录制文件.html",
  "generationDate":new Date(1464253337026.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"IsToolbarShow",
"Level1Navagation"],
  "page":{
    "packageId":"8d5d31712c5f4b57868d6644ec96cd63",
    "type":"Axure:Page",
    "name":"查看录制文件",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7cee7e49cb8a4735b2ba8a3503c90f45",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"290",
            "opacity":"0",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "size":{
              "width":860,
              "height":390},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080f74abf6154711a7eacf6b213dd83f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"290",
                "opacity":"0",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "size":{
                  "width":860,
                  "height":390},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2ef8da1e341486eb1dc0ab1b6831fed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":600,
              "y":353},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 录制管理",
                      "target":{
                        "targetType":"page",
                        "url":"录制管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7f0d67ff270a4950a01e5818683e1689",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":485,
              "y":64},
            "size":{
              "width":217,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521c686b9ae1479791395ede008bc241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":485,
                  "y":64},
                "size":{
                  "width":217,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65286c8725bc4557a3bce679f7783026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":19,
              "y":17},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf892a545184da5bb2aee1e5e1d0013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":19,
                  "y":17},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20e4c3cf6d89429082e798efcbd04e19",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2470a3fb848f4957bf2a4a6c41e1a704"},
{
          "id":"cf7c2450457a4e8892753f0ecd28e3dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"400",
            "location":{
              "x":485,
              "y":107},
            "size":{
              "width":111,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca02b90abb0f46b99eb887cfbb53b29a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"400",
                "location":{
                  "x":485,
                  "y":107},
                "size":{
                  "width":111,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11ef489ec0f3456ca3a06972c815496e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":485,
              "y":149},
            "size":{
              "width":125,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4326dec69f194dc590c80a1d6dcd1482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":485,
                  "y":149},
                "size":{
                  "width":125,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dedd647c1b8a4465bf52e843dba0ab14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":485,
              "y":192},
            "size":{
              "width":139,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4f5b370d959437688f7e341125aa630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":485,
                  "y":192},
                "size":{
                  "width":139,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0c4a73b71194a1f8df032983885a24f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":485,
              "y":234},
            "size":{
              "width":191,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f3a8066032a4d058af2f437c2cdc3df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":485,
                  "y":234},
                "size":{
                  "width":191,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb57895d12bf432e884050408cc12d53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":487,
              "y":277},
            "size":{
              "width":325,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90f1024248dd4338b3f33246019fe99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":487,
                  "y":277},
                "size":{
                  "width":325,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23ae560e788449fc87996441751cade9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":710,
              "y":353},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 录制管理",
                      "target":{
                        "targetType":"page",
                        "url":"录制管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0e4e1acab34a47fe9da9fb389913b99c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":59},
            "size":{
              "width":440,
              "height":291}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"645a02e854bf4e0cb59da6009afd024b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":59},
                "size":{
                  "width":440,
                  "height":291}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实时直播/u21.png"}},
{
          "id":"c5676c0a277241a491c73d3c47721670",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":488,
              "y":310},
            "size":{
              "width":139,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3395c5bb186846ad90605fa512d07374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":488,
                  "y":310},
                "size":{
                  "width":139,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5affc61d282644b9b6bba2c010692720",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":490,
              "y":353},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "2470a3fb848f4957bf2a4a6c41e1a704":{
      "packageId":"2470a3fb848f4957bf2a4a6c41e1a704",
      "type":"Axure:Master",
      "name":"分隔线",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2aefec017034782bd51af1ed331085d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":39},
              "size":{
                "width":801,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0099FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/添加课程/u8_line.png"}},
{
            "id":"a92c12076b914c6ca08653996cf2cfba",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF0099FF},
              "location":{
                "x":19,
                "y":42},
              "size":{
                "width":70,
                "height":3},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0099FF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c111212d4ba1435db57311af88f6b73a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF},
                  "location":{
                    "x":19,
                    "y":42},
                  "size":{
                    "width":70,
                    "height":3},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/添加课程/u9.png"}}]}}},
  "objectPaths":{
    "7cee7e49cb8a4735b2ba8a3503c90f45":{
      "scriptId":"u0"},
    "080f74abf6154711a7eacf6b213dd83f":{
      "scriptId":"u1"},
    "f2ef8da1e341486eb1dc0ab1b6831fed":{
      "scriptId":"u2"},
    "7f0d67ff270a4950a01e5818683e1689":{
      "scriptId":"u3"},
    "521c686b9ae1479791395ede008bc241":{
      "scriptId":"u4"},
    "65286c8725bc4557a3bce679f7783026":{
      "scriptId":"u5"},
    "bbf892a545184da5bb2aee1e5e1d0013":{
      "scriptId":"u6"},
    "20e4c3cf6d89429082e798efcbd04e19":{
      "scriptId":"u7",
      "f2aefec017034782bd51af1ed331085d":{
        "scriptId":"u8"},
      "a92c12076b914c6ca08653996cf2cfba":{
        "scriptId":"u9"},
      "c111212d4ba1435db57311af88f6b73a":{
        "scriptId":"u10"}},
    "cf7c2450457a4e8892753f0ecd28e3dd":{
      "scriptId":"u11"},
    "ca02b90abb0f46b99eb887cfbb53b29a":{
      "scriptId":"u12"},
    "11ef489ec0f3456ca3a06972c815496e":{
      "scriptId":"u13"},
    "4326dec69f194dc590c80a1d6dcd1482":{
      "scriptId":"u14"},
    "dedd647c1b8a4465bf52e843dba0ab14":{
      "scriptId":"u15"},
    "d4f5b370d959437688f7e341125aa630":{
      "scriptId":"u16"},
    "c0c4a73b71194a1f8df032983885a24f":{
      "scriptId":"u17"},
    "6f3a8066032a4d058af2f437c2cdc3df":{
      "scriptId":"u18"},
    "cb57895d12bf432e884050408cc12d53":{
      "scriptId":"u19"},
    "90f1024248dd4338b3f33246019fe99b":{
      "scriptId":"u20"},
    "23ae560e788449fc87996441751cade9":{
      "scriptId":"u21"},
    "0e4e1acab34a47fe9da9fb389913b99c":{
      "scriptId":"u22"},
    "645a02e854bf4e0cb59da6009afd024b":{
      "scriptId":"u23"},
    "c5676c0a277241a491c73d3c47721670":{
      "scriptId":"u24"},
    "3395c5bb186846ad90605fa512d07374":{
      "scriptId":"u25"},
    "5affc61d282644b9b6bba2c010692720":{
      "scriptId":"u26"}}});