$axure.loadCurrentPage({
  "url":"添加课程.html",
  "generationDate":new Date(1464253336108.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"IsToolbarShow",
"Level1Navagation"],
  "page":{
    "packageId":"ddf08efe8bb04361a0096c44acb4bf4d",
    "type":"Axure:Page",
    "name":"添加课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7cee7e49cb8a4735b2ba8a3503c90f45",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"290",
            "opacity":"0",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "size":{
              "width":860,
              "height":460},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080f74abf6154711a7eacf6b213dd83f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"290",
                "opacity":"0",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "size":{
                  "width":860,
                  "height":460},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2ef8da1e341486eb1dc0ab1b6831fed",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":150,
              "y":397},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课表管理",
                      "target":{
                        "targetType":"page",
                        "url":"课表管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7f0d67ff270a4950a01e5818683e1689",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":108},
            "size":{
              "width":61,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521c686b9ae1479791395ede008bc241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":108},
                "size":{
                  "width":61,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65286c8725bc4557a3bce679f7783026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":19,
              "y":17},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf892a545184da5bb2aee1e5e1d0013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":19,
                  "y":17},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20e4c3cf6d89429082e798efcbd04e19",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2470a3fb848f4957bf2a4a6c41e1a704"},
{
          "id":"cf7c2450457a4e8892753f0ecd28e3dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":35,
              "y":151},
            "size":{
              "width":61,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca02b90abb0f46b99eb887cfbb53b29a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":151},
                "size":{
                  "width":61,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11ef489ec0f3456ca3a06972c815496e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":193},
            "size":{
              "width":61,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4326dec69f194dc590c80a1d6dcd1482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":193},
                "size":{
                  "width":61,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dedd647c1b8a4465bf52e843dba0ab14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":236},
            "size":{
              "width":61,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4f5b370d959437688f7e341125aa630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":236},
                "size":{
                  "width":61,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0c4a73b71194a1f8df032983885a24f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":278},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f3a8066032a4d058af2f437c2cdc3df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":278},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb57895d12bf432e884050408cc12d53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":37,
              "y":321},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90f1024248dd4338b3f33246019fe99b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":37,
                  "y":321},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f2ec1db0ac14a4c9a701355cf44869c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":103},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"dc30fec4cb85483aa9c6b39b04f1bc4b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":146},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"66904f46765d49bfab13b1cda1b9ccca",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":189},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"da407083777443808bacd45202ea32ea",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":233},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"e5ce4e366fa14dc5b7cef325edd1e146",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":276},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"00f68e6dc56d410d9b0f7d1ca17b398e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":319},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"23ae560e788449fc87996441751cade9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":260,
              "y":397},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课表管理",
                      "target":{
                        "targetType":"page",
                        "url":"课表管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"57efb14969a9492aa33c8b677e56cbb3",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"13px",
            "location":{
              "x":120,
              "y":361},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebabf37d0064427ea27185eab2808c0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"13px",
                "location":{
                  "x":120,
                  "y":361},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"ad26609848074c5d844a884624b2566a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":35,
              "y":66},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757edc93a84f492c9015a20a18ca052d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":35,
                  "y":66},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"180c0052e9e4410f92872c5e3d1b1936",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":59},
            "size":{
              "width":240,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"42527904795444a0b2f8c4ef80eaa163",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"13px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":220,
              "y":361},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4464c42e4f524b989bfaeb34b43919fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"13px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":361},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "2470a3fb848f4957bf2a4a6c41e1a704":{
      "packageId":"2470a3fb848f4957bf2a4a6c41e1a704",
      "type":"Axure:Master",
      "name":"分隔线",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2aefec017034782bd51af1ed331085d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":39},
              "size":{
                "width":801,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0099FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/添加课程/u8_line.png"}},
{
            "id":"a92c12076b914c6ca08653996cf2cfba",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF0099FF},
              "location":{
                "x":19,
                "y":42},
              "size":{
                "width":70,
                "height":3},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0099FF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c111212d4ba1435db57311af88f6b73a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF},
                  "location":{
                    "x":19,
                    "y":42},
                  "size":{
                    "width":70,
                    "height":3},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/添加课程/u9.png"}}]}}},
  "objectPaths":{
    "7cee7e49cb8a4735b2ba8a3503c90f45":{
      "scriptId":"u0"},
    "080f74abf6154711a7eacf6b213dd83f":{
      "scriptId":"u1"},
    "f2ef8da1e341486eb1dc0ab1b6831fed":{
      "scriptId":"u2"},
    "7f0d67ff270a4950a01e5818683e1689":{
      "scriptId":"u3"},
    "521c686b9ae1479791395ede008bc241":{
      "scriptId":"u4"},
    "65286c8725bc4557a3bce679f7783026":{
      "scriptId":"u5"},
    "bbf892a545184da5bb2aee1e5e1d0013":{
      "scriptId":"u6"},
    "20e4c3cf6d89429082e798efcbd04e19":{
      "scriptId":"u7",
      "f2aefec017034782bd51af1ed331085d":{
        "scriptId":"u8"},
      "a92c12076b914c6ca08653996cf2cfba":{
        "scriptId":"u9"},
      "c111212d4ba1435db57311af88f6b73a":{
        "scriptId":"u10"}},
    "cf7c2450457a4e8892753f0ecd28e3dd":{
      "scriptId":"u11"},
    "ca02b90abb0f46b99eb887cfbb53b29a":{
      "scriptId":"u12"},
    "11ef489ec0f3456ca3a06972c815496e":{
      "scriptId":"u13"},
    "4326dec69f194dc590c80a1d6dcd1482":{
      "scriptId":"u14"},
    "dedd647c1b8a4465bf52e843dba0ab14":{
      "scriptId":"u15"},
    "d4f5b370d959437688f7e341125aa630":{
      "scriptId":"u16"},
    "c0c4a73b71194a1f8df032983885a24f":{
      "scriptId":"u17"},
    "6f3a8066032a4d058af2f437c2cdc3df":{
      "scriptId":"u18"},
    "cb57895d12bf432e884050408cc12d53":{
      "scriptId":"u19"},
    "90f1024248dd4338b3f33246019fe99b":{
      "scriptId":"u20"},
    "5f2ec1db0ac14a4c9a701355cf44869c":{
      "scriptId":"u21"},
    "dc30fec4cb85483aa9c6b39b04f1bc4b":{
      "scriptId":"u22"},
    "66904f46765d49bfab13b1cda1b9ccca":{
      "scriptId":"u23"},
    "da407083777443808bacd45202ea32ea":{
      "scriptId":"u24"},
    "e5ce4e366fa14dc5b7cef325edd1e146":{
      "scriptId":"u25"},
    "00f68e6dc56d410d9b0f7d1ca17b398e":{
      "scriptId":"u26"},
    "23ae560e788449fc87996441751cade9":{
      "scriptId":"u27"},
    "57efb14969a9492aa33c8b677e56cbb3":{
      "scriptId":"u28"},
    "ebabf37d0064427ea27185eab2808c0f":{
      "scriptId":"u29"},
    "ad26609848074c5d844a884624b2566a":{
      "scriptId":"u30"},
    "757edc93a84f492c9015a20a18ca052d":{
      "scriptId":"u31"},
    "180c0052e9e4410f92872c5e3d1b1936":{
      "scriptId":"u32"},
    "42527904795444a0b2f8c4ef80eaa163":{
      "scriptId":"u33"},
    "4464c42e4f524b989bfaeb34b43919fe":{
      "scriptId":"u34"}}});