$axure.loadCurrentPage({
  "url":"添加教室.html",
  "generationDate":new Date(1464253337464.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"IsToolbarShow",
"Level1Navagation"],
  "page":{
    "packageId":"95f2e0df13b442da9acd800c956be705",
    "type":"Axure:Page",
    "name":"添加教室",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"20e4c3cf6d89429082e798efcbd04e19",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2470a3fb848f4957bf2a4a6c41e1a704"},
{
          "id":"289d325a81d6423e9b691db7b472a162",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"290",
            "opacity":"0",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFCCCCCC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "size":{
              "width":860,
              "height":390},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"065b6c2643bd4765beda070379d626b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"290",
                "opacity":"0",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFCCCCCC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "size":{
                  "width":860,
                  "height":390},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7984c64596da4803bd50073d9eee68ad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":360,
              "y":340},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教室管理",
                      "target":{
                        "targetType":"page",
                        "url":"教室管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"05f617a83e144bba8042cdf5fef2c308",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":59},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1081ff5aa550467897ac49e32b98fd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":59},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b85756198a6b46169e1d50ebb26a2ba9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "location":{
              "x":19,
              "y":17},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69b593f87b7b4e2088f9b0302b562704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "location":{
                  "x":19,
                  "y":17},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee0c7bf2ea0046938fe01244d08dede0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":102},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed86550f04542d3875628ed29ed6fd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":102},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4d80ab19c354bde97617ee6b9642acd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":144},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adecf7240e2c4b0b9e5674d3036a0baa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":144},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6764abc9cdea40c48777c31ae326c8e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":222},
            "size":{
              "width":61,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05d89e85b57d47f5a386c12f1d148e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":222},
                "size":{
                  "width":61,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d62748c283148f58fe3c4794e23503f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":54},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"971cdddad47441a2a74bec3f24c0cdb3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":470,
              "y":340},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教室管理",
                      "target":{
                        "targetType":"page",
                        "url":"教室管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ed8bb173d5e044f0a7f3ca8fd445c4a1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":97},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"109f01946feb4a518e983c81269dc02c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":139},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"381f080ae7d94149bff85c33c395c2ef",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":222},
            "size":{
              "width":450,
              "height":93}},
          "adaptiveStyles":{
}},
{
          "id":"19ea13af44d14bd1af7a39928c105bfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":380,
              "y":62},
            "size":{
              "width":183,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2b37f95ea6b4bc68b7cde9d406499ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":380,
                  "y":62},
                "size":{
                  "width":183,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e99fedea4d4449889a4d5e02c1c47a41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":380,
              "y":102},
            "size":{
              "width":191,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92648671882f41fcaa553f138f2d757e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":380,
                  "y":102},
                "size":{
                  "width":191,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c313e9bb8aa4131a435c9db845d10ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":380,
              "y":145},
            "size":{
              "width":379,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aa55fed85394b6dbd69d95e9ec2b752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":380,
                  "y":145},
                "size":{
                  "width":379,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60a341495cb54a5c95eab3f8070193aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":590,
              "y":187},
            "size":{
              "width":199,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6702a52df38341bb87434eeb57859c0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":590,
                  "y":187},
                "size":{
                  "width":199,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c28aa4789fc048aab35b7912b4db4a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":35,
              "y":186},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e44372c350954d85ab40256817ebcdff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":35,
                  "y":186},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0f3e43b87624194aba14a2669108858",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":120,
              "y":181},
            "size":{
              "width":240,
              "height":32}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "2470a3fb848f4957bf2a4a6c41e1a704":{
      "packageId":"2470a3fb848f4957bf2a4a6c41e1a704",
      "type":"Axure:Master",
      "name":"分隔线",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2aefec017034782bd51af1ed331085d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":19,
                "y":39},
              "size":{
                "width":801,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0099FF}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/添加课程/u8_line.png"}},
{
            "id":"a92c12076b914c6ca08653996cf2cfba",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF0099FF},
              "location":{
                "x":19,
                "y":42},
              "size":{
                "width":70,
                "height":3},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF0099FF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c111212d4ba1435db57311af88f6b73a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF},
                  "location":{
                    "x":19,
                    "y":42},
                  "size":{
                    "width":70,
                    "height":3},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/添加课程/u9.png"}}]}}},
  "objectPaths":{
    "20e4c3cf6d89429082e798efcbd04e19":{
      "scriptId":"u0",
      "f2aefec017034782bd51af1ed331085d":{
        "scriptId":"u1"},
      "a92c12076b914c6ca08653996cf2cfba":{
        "scriptId":"u2"},
      "c111212d4ba1435db57311af88f6b73a":{
        "scriptId":"u3"}},
    "289d325a81d6423e9b691db7b472a162":{
      "scriptId":"u4"},
    "065b6c2643bd4765beda070379d626b4":{
      "scriptId":"u5"},
    "7984c64596da4803bd50073d9eee68ad":{
      "scriptId":"u6"},
    "05f617a83e144bba8042cdf5fef2c308":{
      "scriptId":"u7"},
    "1081ff5aa550467897ac49e32b98fd18":{
      "scriptId":"u8"},
    "b85756198a6b46169e1d50ebb26a2ba9":{
      "scriptId":"u9"},
    "69b593f87b7b4e2088f9b0302b562704":{
      "scriptId":"u10"},
    "ee0c7bf2ea0046938fe01244d08dede0":{
      "scriptId":"u11"},
    "1ed86550f04542d3875628ed29ed6fd8":{
      "scriptId":"u12"},
    "d4d80ab19c354bde97617ee6b9642acd":{
      "scriptId":"u13"},
    "adecf7240e2c4b0b9e5674d3036a0baa":{
      "scriptId":"u14"},
    "6764abc9cdea40c48777c31ae326c8e8":{
      "scriptId":"u15"},
    "05d89e85b57d47f5a386c12f1d148e91":{
      "scriptId":"u16"},
    "4d62748c283148f58fe3c4794e23503f":{
      "scriptId":"u17"},
    "971cdddad47441a2a74bec3f24c0cdb3":{
      "scriptId":"u18"},
    "ed8bb173d5e044f0a7f3ca8fd445c4a1":{
      "scriptId":"u19"},
    "109f01946feb4a518e983c81269dc02c":{
      "scriptId":"u20"},
    "381f080ae7d94149bff85c33c395c2ef":{
      "scriptId":"u21"},
    "19ea13af44d14bd1af7a39928c105bfd":{
      "scriptId":"u22"},
    "e2b37f95ea6b4bc68b7cde9d406499ce":{
      "scriptId":"u23"},
    "e99fedea4d4449889a4d5e02c1c47a41":{
      "scriptId":"u24"},
    "92648671882f41fcaa553f138f2d757e":{
      "scriptId":"u25"},
    "2c313e9bb8aa4131a435c9db845d10ac":{
      "scriptId":"u26"},
    "5aa55fed85394b6dbd69d95e9ec2b752":{
      "scriptId":"u27"},
    "60a341495cb54a5c95eab3f8070193aa":{
      "scriptId":"u28"},
    "6702a52df38341bb87434eeb57859c0e":{
      "scriptId":"u29"},
    "c28aa4789fc048aab35b7912b4db4a9f":{
      "scriptId":"u30"},
    "e44372c350954d85ab40256817ebcdff":{
      "scriptId":"u31"},
    "c0f3e43b87624194aba14a2669108858":{
      "scriptId":"u32"}}});